---
- name: add the kubernetes yum repo key
  yum_repository:
    name: kubernetes
    description: the kubernetes yum repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgcheck: True
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: install the kubernetes yum packages
  yum:
    name: "{{ item }}"
    allow_downgrade: True
  with_items:
    - "kubelet-{{ kubernetes.version|kube_platform_version('redhat') }}"
    - "kubeadm-{{ kubernetes.version|kube_platform_version('redhat') }}"
    - "kubectl-{{ kubernetes.version|kube_platform_version('redhat') }}"
    - "kubernetes-cni-{{kubernetes.cni_version|kube_platform_version('redhat')}}"
