---
- name: make cni directory
  file:
    dest: /opt/cni
    state: directory

- name: download and unpack the cni plugins
  unarchive:
    src: "https://storage.googleapis.com/kubernetes-release/network-plugins/cni-amd64-{{ cni.release }}.tar.gz"
    dest: /opt/cni
    remote_src: yes
