---
- name: add docker apt key
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add docker apt repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower}}-{{ ansible_distribution_release|lower }} main"
    update_cache: true

- name: install docker
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker-engine={{ docker.debian.version }}"

- name: install docker-py
  pip:
    name: docker-py
