---
- hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
  - name: install python
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip)"
    register: output
    changed_when: output.stdout != ""

- name: install provider pre-reqs
  hosts: all
  become: yes
  roles:
    - role: aws
      when: provider is defined and provider|lower == "aws"
