---
- set_fact:
    kubernetes_node_ip: "{{ hostvars[inventory_hostname]['ansible_'~item]['ipv4']['address'] }}"
  with_items:
     - enp0s8

- name: drop vagrant node ip flag for the kubelet
  template:
    dest: /etc/systemd/system/kubelet.service.d/09-vagrant.conf
    src: etc/systemd/system/kubelet.service.d/09-vagrant.conf
  when: vagrant_host == True
  notify:
    - restart kubelet
